Trello/boards/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextField, BooleanField
from wtforms.validators import DataRequired, Length


class AddABoardForm(FlaskForm):
    name = StringField('Add a new board', validators=[
                       Length(max=100), DataRequired()])
    description = TextField('Add a board description')
    is_private = BooleanField('is the board private??')
    submit = SubmitField('Add')


class UpdateABoardForm(FlaskForm):
    name = StringField('Add a new board', validators=[
                       Length(max=100), DataRequired()])
    description = TextField('Add a board description')
    is_private = BooleanField('is the board private??')
    submit = SubmitField('Update')

Trello/cards/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextField
from wtforms.validators import DataRequired, Length


class AddACardForm(FlaskForm):
    name = StringField('Add a new card', validators=[
                       Length(max=100), DataRequired()])
    description = TextField('Add a card description')
    submit = SubmitField('Add')


class UpdateACardForm(FlaskForm):
    name = StringField('Add a new card', validators=[
                       Length(max=100), DataRequired()])
    description = TextField('Add a card description')
    submit = SubmitField('Update')

Trello/members/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField
from wtforms.validators import DataRequired


class AddAMemberForm(FlaskForm):
    add_member = SelectField('Add a new member', choices=[])
    submit = SubmitField('Add')

Trello/authentication/routes.py
from flask import Blueprint
from Trello import bcrypt, db
from flask import render_template, url_for, request, redirect, flash
from flask_login import logout_user, login_required, login_user, current_user
from Trello.authentication.forms import LoginForm, RegisterForm
from Trello.models import Users

authentication = Blueprint('authentication', __name__)


@authentication.route("/signup", methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('boards.my_boards', user=current_user.username))
    form = RegisterForm()
    if request.method == 'POST' and form.validate():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = Users(username=form.username.data,
                     email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Wellcome {form.username.data}', 'success')
        login_user(user)
        return redirect(url_for('boards.my_boards', user=user.username))
    return render_template('signup.html', page_title='signup', form=form)


@authentication.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('boards.my_boards', user=current_user.username))
    form = LoginForm()
    if request.method == 'POST' and form.validate():
        user = Users.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            return redirect(url_for('boards.my_boards', user=user.username))
        else:
            flash("Either the email or the password was Incorrect please try again",'warning')
    return render_template('login.html', page_title='login', form=form)


@authentication.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('authentication.login'))

Trello/boards/routes.py
from flask import Blueprint, abort
from Trello import app, db, es
from flask import render_template, url_for, request, redirect, flash
from flask_login import current_user, login_required
from Trello.boards.forms import AddABoardForm, UpdateABoardForm
from Trello.models import Boards, BoardMembers
from Trello.authorization import third_level_authorization, second_level_authorization
from Trello.services import fetch_all_shared_boards, check_if_search_is_enabled

boards = Blueprint("boards", __name__)
search_enabled = check_if_search_is_enabled()


def add_a_board_into_the_database(form):
    board = Boards(
        user_id=current_user.id,
        name=form.name.data,
        description=form.description.data,
        is_private=form.is_private.data,
    )
    board.members.append(BoardMembers(member_id=current_user.id, is_admin=True))
    db.session.add(board)
    db.session.commit()
    print(search_enabled, "search_enabled")
    if search_enabled:
        print('ho')
        add_a_board_into_es(board)
    return board


def add_a_board_into_es(board):
    a_board = {
        "user_id": board.user_id,
        "name": board.name,
        "description": board.description,
        "is_private": board.is_private,
        "url": f"{board.owner.username}/boards/{board.id}",
        "members": [current_user.id],
    }
    es.index(index="boards", id=int(board.id), body=a_board)


def fetch_all_boards():
    all_boards = Boards.query.filter_by(user_id=current_user.id).all()
    return all_boards


@boards.route("/<user>/boards", methods=["GET", "POST"])
@login_required
def my_boards(user):
    form = AddABoardForm()
    if request.method == "POST" and form.validate():
        board = add_a_board_into_the_database(form)
        flash(
            f'Added board "{form.name.data}"..... click the board to view more',
            "success",
        )
        return redirect(
            url_for("cards.my_board", user=current_user.username, board=board.id)
        )
    all_boards = fetch_all_boards()
    all_shared_boards = fetch_all_shared_boards(current_user.id)
    return render_template(
        "my-boards.html",
        page_title="my board",
        form=form,
        all_boards=all_boards,
        all_shared_boards=all_shared_boards,
    )


@boards.route("/<user>/boards/create-first-board")
@login_required
def create_first_board(user):
    return render_template("create-first-board.html", page_title="create first board")


def remove_a_board_from_the_database(the_board):
    db.session.delete(the_board)
    if search_enabled:
        delete_a_board_from_es(the_board)
    db.session.commit()


def delete_a_board_from_es(the_board):
    es.delete(index="boards", id=int(the_board.id))
    query = {"query": {"match": {"board_id": the_board.id}}}
    es.delete_by_query(index="cards", body=query)


@boards.route("/delete-board/<board>")
def delete_board(board):
    the_board = Boards.query.get(board)
    if the_board:
        if second_level_authorization(the_board.id):
            remove_a_board_from_the_database(the_board)
            flash(f"removed board {the_board.name}", "success")
            return redirect(url_for("boards.my_boards", user=current_user.username))
        else:
            abort(400)
    else:
        abort(404)


def update_board_in_database(the_board, form):
    the_board.name = form.name.data
    the_board.description = form.description.data
    the_board.is_private = form.is_private.data
    db.session.commit()
    if search_enabled:
        update_a_board_into_es(the_board, form)


def update_a_board_into_es(board, form):
    the_board = es.get(index="boards", id=int(board.id))
    the_board["_source"]["name"] = form.name.data
    the_board["_source"]["description"] = form.description.data
    the_board["_source"]["is_private"] = form.is_private.data
    body = the_board["_source"]
    es.index(index="boards", id=int(board.id), body=body)


def set_update_board_form_text(the_board, form):
    form.name.data = the_board.name
    form.description.data = the_board.description
    form.is_private.data = the_board.is_private


@boards.route("/update-board/<board>", methods=["GET", "POST"])
@login_required
def update_board(board):
    the_board = Boards.query.get(board)
    if the_board:
        if second_level_authorization(the_board.id):
            form = UpdateABoardForm()
            if request.method == "POST" and form.validate():
                update_board_in_database(the_board, form)
                flash(f"updated board {the_board.name}", "success")
                return redirect(url_for("boards.my_boards", user=current_user.username))
            set_update_board_form_text(the_board, form)
            return render_template("update-board.html", form=form)
        else:
            abort(400)
    else:
        abort(404)

Trello/cards/routes.py
from flask import Blueprint, abort
from Trello import app, db, es
from flask import render_template, url_for, request, redirect, flash
from flask_login import current_user, login_required
from Trello.cards.forms import AddACardForm, UpdateACardForm
from Trello.services import fetch_all_board_members_info, check_if_search_is_enabled
from Trello.models import Boards, Cards, Checklist, ChecklistItems
from Trello.authorization import (
    first_level_authorization,
    second_level_authorization,
    second_level_authorization_can_edit,
    third_level_authorization,
)


cards = Blueprint("cards", __name__)
search_enabled = check_if_search_is_enabled()


def add_a_card_to_the_database(a_board, form):
    card = Cards(
        board_id=a_board.id, name=form.name.data, description=form.description.data
    )
    db.session.add(card)
    db.session.commit()
    if search_enabled:
        add_a_card_to_es(card)
    return card


def get_board_members_id_in_array(board_id):
    array_of_all_member_id = []
    all_board_members_info, board_members_name = fetch_all_board_members_info(board_id)
    for board_member in all_board_members_info:
        print(board_member["board_member_info"])
        array_of_all_member_id.append(board_member["board_member_info"].id)

    return array_of_all_member_id


def add_a_card_to_es(card):
    the_card = {
        "board_id": card.board_id,
        "name": card.name,
        "description": card.description,
        "url": f"{card.board.owner.username}/boards/{card.board.id}/cards/{card.id}",
        "members": get_board_members_id_in_array(card.board.id),
    }

    es.index(index="cards", id=int(card.id), body=the_card)


@cards.route("/<user>/boards/<board>", methods=["GET", "POST"])
def my_board(user, board):
    can_edit = False
    a_board = Boards.query.filter_by(id=board).first()
    if a_board:
        if second_level_authorization(board):
            form = AddACardForm()
            if request.method == "POST" and form.validate():
                card = add_a_card_to_the_database(a_board, form)
                flash("Added a new card", "success")
                return redirect(
                    url_for("checklists.card", user=user, board=board, card=card.id)
                )
            if second_level_authorization_can_edit(board):
                can_edit = True
            return render_template(
                "board.html",
                page_title="board",
                board=a_board,
                form=form,
                can_edit=can_edit,
            )
        else:
            abort(400)
    else:
        abort(404)


def delete_a_card_from_the_database(the_card):
    db.session.delete(the_card)
    db.session.commit()
    if search_enabled:
        delete_a_card_from_es(the_card)


def delete_a_card_from_es(the_card):
    es.delete(index="cards", id=int(the_card.id))


@cards.route("/delete-card/<card>")
@login_required
def delete_card(card):
    the_card = Cards.query.get(card)
    if the_card:
        if second_level_authorization(the_card.board.id):
            delete_a_card_from_the_database(the_card)
            flash(f"removed card {the_card.name}", "success")
            return redirect(
                url_for(
                    "cards.my_board",
                    user=current_user.username,
                    board=the_card.board.id,
                )
            )
        else:
            abort(400)
    else:
        abort(404)


def update_a_card_in_database(the_card, form):
    the_card.name = form.name.data
    the_card.description = form.description.data
    db.session.commit()
    if search_enabled:
        update_a_card_in_es(the_card, form)


def update_a_card_in_es(the_card, form):
    a_card = {
        "name": form.name.data,
        "description": form.description.data,
    }
    es.index(index="cards", id=int(the_card.id), body=a_card)


def update_a_card_form_filler(the_card, form):
    form.name.data = the_card.name
    form.description.data = the_card.description


@cards.route("/update-card/<card>", methods=["GET", "POST"])
@login_required
def update_card(card):
    the_card = Cards.query.get(card)
    if the_card:
        if second_level_authorization(the_card.board.id):
            form = UpdateACardForm()
            if request.method == "POST" and form.validate():
                update_a_card_in_database(the_card, form)
                flash(f"updated card {the_card.name}", "success")
                return redirect(
                    url_for(
                        "cards.my_board",
                        user=current_user.username,
                        board=the_card.board.id,
                    )
                )
            update_a_card_form_filler(the_card, form)
            return render_template("update-card.html", form=form)
        else:
            abort(400)
    else:
        abort(404)


@cards.route("/<user>/boards/<board>/cards", methods=["GET", "POST"])
def redirect_to_board(user, board):
    return redirect(url_for("cards.my_board", user=user, board=board))

Trello/main/routes.py
from flask import Blueprint
from flask import render_template
from Trello.models import Boards, Users
from Trello import es, celery, redis_client
from flask import request, redirect, url_for
from flask_login import current_user
from Trello.services import fetch_all_shared_boards


main = Blueprint("main", __name__)


@main.route("/")
def home():
    if current_user.is_authenticated:
        return redirect(url_for("boards.my_boards", user=current_user.username))
    else:
        boards = Boards.query.filter_by(is_private=False).all()
        return render_template("home.html", page_title="home", boards=boards)


@celery.task()
def fetch_user_data(user_id):
    all_user_boards = str(Boards.query.filter_by(user_id=user_id).all())
    all_shared_boards = str(fetch_all_shared_boards(user_id))
    user_information = str(Users.query.filter_by(id=user_id).first())

    return [all_shared_boards, all_user_boards, user_information]


@main.route("/<username>/download_data")
def download_user_data(username):
    user_data = fetch_user_data.apply_async(args=[current_user.id], countdown=10)
    return user_data.id


@main.route("/data_status/<task_id>")
def status_data(task_id):
    user_data = fetch_user_data.AsyncResult(task_id)
    return user_data.status


@main.route("/get_data/<task_id>")
def get_data(task_id):
    user_data = redis_client.get("celery-task-meta-" + task_id)
    redis_client.delete("celery-task-meta-" + task_id)
    return user_data


@main.route("/search", methods=["GET", "POST"])
def search():
    params = request.get_json()
    if not params:
        params = {}
        params["searchKeyword"] = request.args.get("q")
    print(params["searchKeyword"])
    if current_user.is_authenticated:
        query = {
            "query": {
                "dis_max": {
                    "queries": [
                        {
                            "bool": {
                                "must": [
                                    {
                                        "match_phrase_prefix": {
                                            "name": params["searchKeyword"]
                                        }
                                    },
                                    {"term": {"members": current_user.id}},
                                ]
                            }
                        },
                        {
                            "bool": {
                                "must": [
                                    {
                                        "match_phrase_prefix": {
                                            "name": params["searchKeyword"]
                                        }
                                    },
                                    {"match": {"is_private": "false"}},
                                ]
                            }
                        },
                    ],
                    "tie_breaker": 0.7,
                }
            }
        }
        searched = es.search(body=query)
    else:
        query = {
            "query": {
                "bool": {
                    "must": [
                        {"match_phrase_prefix": {"name": params["searchKeyword"]}},
                        {"match": {"is_private": "false"}},
                    ]
                }
            }
        }
        searched = es.search(body=query)
    return searched

Trello/users/routes.py
from flask import Blueprint
from flask import render_template
from flask_login import login_required


users = Blueprint('users', __name__)


@users.route("/<user>/account")
def account(user):
    return render_template("account.html")

Trello/templates/bad-request.html
{% extends 'layout.html' %}
{% block content %}
<div class="container mt-4">
<p class="display-1 text-center">Bad request</p>
<p class="text-muted text-center">Maybe you are not authorised to access the page or there is some problem with your input</p>
</div>
{% endblock %}

Trello/templates/board.html
{% extends 'layout.html' %}
{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        {% if current_user.is_authenticated %}
        <li class="breadcrumb-item"><a href="{{ url_for('boards.my_boards',user=current_user.username) }}">My
                boards</a></li>
        {% else %}
        <li class="breadcrumb-item"><a href="{{ url_for('main.home') }}">Public
                boards</a></li>
        {% endif %}
        <li class="breadcrumb-item active"><a>{{ board.name }}</a></li>
    </ol>
</nav>
<div class="pt-5 pr-5 pl-5 container-fluid">
    {% if can_edit %}
    <a class="btn btn-warning float-right" href="{{ url_for('members.board_members',user=current_user.username,board=board.id) }}">Members</a>
    {% endif %}
    <p class="display-4 mt-3">{{ board.name }}</p>
    <p class="text-muted">Owner: {{ board.owner.username }}</p>
    {% if board.is_private %}
    <span class="badge badge-primary">Private board</span>
    {% else %}
    <span class="badge badge-secondary">Public board</span>
    {% endif %}
    <p class="h1 mt-4">Cards :</p>
</div>

<div class="row pb-5 pt-0 m-0">
    {% if can_edit %}
    <form method="post" class="border m-3 p-4 bg-white col-lg-6 shadow-sm">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.name.label(class="form-control-label") }}
            {% if form.name.errors %}
            {{ form.name(class="form-control is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.name.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.name(class="form-control") }}
            {% endif %}

        </div>

        <div class="form-group">
            {{ form.description.label(class="form-control-label") }}
            {% if form.description.errors %}
            {{ form.description(class="form-control is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.description.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.description(class="form-control") }}
            {% endif %}

        </div>

        <div class="form-group">
            {{form.submit(class='btn btn-outline-success')}}
        </div>
    </form>
    {% endif %}
    {% if board.cards|length == 0 %}
    <p class="text-muted m-3 border shadow-sm d-flex justify-content-center align-items-center p-5">No cards for this board...</p>
    {% endif %}
    {% for card in board.cards %}
    <div class="border p-4 col m-3 shadow-sm rounded badge-warning d-flex flex-column justify-content-between">
        <a href="{{ url_for('checklists.card',user=board.owner.username,board=board.id,card=card.id) }}"
            class="btn btn-fluid container border p-5 mt-3 mb-4 d-flex flex-column justify-content-start align-items-start bg-warning">
            <p class="h1">{{ card.name }}</p>
            {% if card.description %}
            <p class="text"> {{ card.description }} </p>
            {% else %}
            <p class="text-muted">No description</p>
            {% endif %}
        </a>
        <div class="d-flex justify-content-around">
            {% if can_edit %}
            <a href="{{ url_for('cards.delete_card',card=card.id) }}" class="btn btn-danger mr-4">Delete</a>
            <a href="{{ url_for('cards.update_card',card=card.id) }}" class="btn btn-secondary">Update</a>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>

</div>
{% endblock %}

Trello/templates/create-first-board.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
    <h1 class="display-1">Create First Board</h1>
</div>
{% endblock %}

Trello/templates/home.html
{% extends 'layout.html' %}
{% block content %}
<div class="container-fluid">
    <h1 class="display-4 m-3">Public cards</h1>
    {% if boards|length == 0 %}
    <p class="container-fluid border p-4 mt-3 mb-3 d-flex flex-column justify-content-start align-items-start">No Public
        boards available</p>
    {% endif %}
    <div class="row">
        {% for board in boards %}
        <a href="{{ url_for('cards.my_board',user=board.owner.username,board=board.id) }}"
            class="btn btn-fluid container border p-5 m-4 d-flex flex-column justify-content-between align-items-start shadow-sm col-lg bg-warning">
            <p class="display-4 float-left border-bottom">{{ board.name }}</p>
            <div class="d-flex flex-column align-items-start">
                <small class="text-muted mb-3">owner: {{ board.owner.username }}</small>
                <span class="badge badge-secondary pr-2 pl-2">Public</span>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}

Trello/templates/layout.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{{ url_for('static',filename='styles/main.css') }}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    {% if page_title %}
    <title>Trello.com {{page_title}}</title>
    {% else %}
    <title>Trello.com</title>
    {% endif %}
</head>

<body class="bg-light">
    <nav class="navbar navbar-expand-lg transperent-1 navbar-light bg-white p-4 shadow-sm">
        <div class="container-fluid">
            {% if current_user.is_authenticated %}
            <a class="navbar-brand" href="{{ url_for('boards.my_boards',user=current_user.username) }}">Trello.com</a>
            {% else %}
            <a class="navbar-brand" href="{{ url_for('main.home') }}">Trello.com</a>
            {% endif %}
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    {% if current_user.is_authenticated %}
                    <li class=" nav-item">
                        <a class="nav-link" href="{{ url_for('users.account',user=current_user.id) }}"><i>{{ current_user.email}}</i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('authentication.logout') }}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('authentication.login') }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('authentication.signup') }}">Register</a>
                    </li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }} alert-dismissible fade show">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">x</span>
        </button>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    <!-- <ul class="navbar-nav w-100 border-bottom" id='search'>
        <li class=" nav-item mr-auto ml-auto position-relative w-75">
            <a class="nav-link " href="#"><input id="search-bar" placeholder="Search"
                    class="form-control ml-lg-auto mr-lg-auto" type="text">
                <ul id='search-results' class="position-absolute list-group w-100">

                </ul>
            </a>
        </li>
    </ul> -->
    {% block content %}{% endblock %}
    <!-- <script src="{{ url_for('static',filename='scripts/search.js') }}"></script> -->
</body>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
</body>

</html>

Trello/templates/my-boards.html
{% extends 'layout.html' %}
{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a">All boards</a>
        </li>
    </ol>
</nav>
<h1 class="display-4 ml-4">My Boards</h1>

<div class="m-4 row">
    <form method="post"
        class="border p-4 mt-2 mb-2 mr-1 ml-1 bg-white shadow-sm col-lg-6 d-flex flex-column justify-content-around">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.name.label(class="form-control-label") }}
            {% if form.name.errors %}
            {{ form.name(class="form-control is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.name.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.name(class="form-control") }}
            {% endif %}

        </div>

        <div class="form-group">
            {{ form.description.label(class="form-control-label") }}
            {% if form.description.errors %}
            {{ form.description(class="form-control is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.description.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.description(class="form-control") }}
            {% endif %}

        </div>


        <div class="form-group">
            {{ form.is_private.label(class="form-control-label") }}
            {% if form.is_private.errors %}
            {{ form.is_private(class="is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.is_private.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.is_private(class="") }}
            {% endif %}

        </div>
        <div class="form-group">
            {{form.submit(class='btn btn-outline-success')}}
        </div>
    </form>

    {% if all_boards|length ==0 %}
    <p
        class="text-muted container p-3 mt-2 mb-2 mr-1 ml-1 d-flex justify-content-center align-items-center border p-3 col shadow-sm">
        No personal boards available....</p>
    {% endif %}

    {% for board in all_boards %}
    <div class="border p-4 mt-2 mb-2 mr-1 ml-1 shadow-sm d-flex flex-column justify-content-between bg-warning col">
        <a href="{{ url_for('cards.my_board',user=board.owner.username,board=board.id) }}"
            class="btn btn-fluid container p-4 pb-0 mt-3 mb-0 d-flex flex-column justify-content-between align-items-start">
            <p class="h1 text-left">{{ board.name }}</p>
            <div class="text-left mb-2">
                <span class="badge badge-secondary">My board</span>
                {% if board.is_private %}
                <span class="badge badge-dark">Private</span>
                {% else %}
                <span class="badge badge-light">Public</span>
                {% endif %}
            </div>
            {% if board.description %}
            <p> {{ board.description }} </p>
            {% else %}
            <p class="text-muted">No description </p>
            {% endif %}
        </a>
        <div class="d-flex justify-content-around border-top pt-4">
            <a href="{{ url_for('boards.delete_board',board=board.id) }}" class="btn btn-danger mr-4">Delete</a>
            <a href="{{ url_for('boards.update_board',board=board.id) }}" class="btn btn-secondary">Update</a>
        </div>
    </div>
    {% endfor %}

    {% for board in all_shared_boards %}
    <div class="border p-4 mt-2 mb-2 mr-1 ml-1 shadow-sm d-flex flex-column justify-content-between bg-warning col">
        <a href="{{ url_for('cards.my_board',user=board.owner.username,board=board.id) }}"
            class="btn btn-fluid container p-4 pb-0 mt-3 mb-0 d-flex flex-column justify-content-between align-items-start">
            <p class="h1 text-left">{{ board.name }}</p>
            <div class="text-left mb-2">
                <span class="badge badge-success">Owner: {{ board.owner.username }}</span>
                <span class="badge badge-secondary">Shared board</span>
                {% if board.is_private %}
                <span class="badge badge-dark">Private</span>
                {% else %}
                <span class="badge badge-light">Public</span>
                {% endif %}
            </div>
            {% if board.description %}
            <p> {{ board.description }} </p>
            {% else %}
            <p class="text-muted">No description </p>
            {% endif %}
        </a>
        <div class="d-flex justify-content-around border-top pt-4">
            <a href="{{ url_for('boards.delete_board',board=board.id) }}" class="btn btn-danger mr-4">Delete</a>
            <a href="{{ url_for('boards.update_board',board=board.id) }}" class="btn btn-secondary">Update</a>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}